### ISSUE TITLE
[Feature Request] QWERTY layer support

### ISSUE THREAD

**Issue by metalgear8019** [metalgear8019/qmk_firmware#3]
The modified P40 Ortho keymap is in Workman layout.
It would be nice to have a keybinding that could switch it back to QWERTY when needed.

## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

A feature that could switch from Workman to QWERTY with an assigned keybinding

## Task List

- [ ] Add a layer for QWERTY
- [ ] Choose a keybinding for the layer switch 
- [ ] Install and test firmware
